import os
import sys
import json
from common import read_input, write_output, call_llm

def get_fallback_data(user_message, profile, results, stored_memory):
    target = profile.get("careerGoal", "software engineer")
    ats_score = results.get("resumeAnalysis", {}).get("atsScore", 75) if results else 75
    skills_count = len(profile.get("knownSkills", [])) if profile.get("knownSkills") else 0
    
    gaps_list = []
    if results and results.get("skillGaps"):
        gaps_list = [sg.get("skillName") for sg in results.get("skillGaps") if isinstance(sg, dict)]
    gaps_str = ", ".join(gaps_list[:3]) if gaps_list else "None determined Yet"
    
    mem_list = []
    if stored_memory:
        mem_list = [m.get("note") for m in stored_memory if isinstance(m, dict)]
    mem_str = "; ".join(mem_list) if mem_list else "No active custom notes configured."
    
    connected_reply = f"""As your specialized AI Career Mentor, I am actively reviewing your portfolio. Let's build your pathway to being an elite **{target}**!
      
Here is your live telemetry integration summary:
- **Background**: {profile.get("degree", "Technology Graduate")} with {profile.get("experienceLevel", "Junior")} experience.
- **Resume Integrity**: ATS Score is mapped at {ats_score}%.
- **Tech Skill Coverage**: {skills_count} validated technical skills.
- **Top Goal Gaps**: {gaps_str}.
- **Stored Memory Notes**: {mem_str}

I've activated the local offline knowledge retrieval system. You can draft an immersive **7-Day Study Plan** or choose quick targets on the dashboard list below!"""

    is_plan = "study plan" in user_message.lower() or "7-day" in user_message.lower()
    
    html_snippet = None
    if is_plan:
        html_snippet = f"""
          <div class="space-y-3 p-4 bg-slate-900 rounded-xl border border-cyan-500/20">
            <h5 class="text-xs font-mono font-bold text-cyan-400">7-DAY CUSTOM SYLLABUS — EXPERT ALIGNMENT</h5>
            <ol class="space-y-2 text-xs text-gray-300 list-decimal list-inside">
              <li><strong class="text-white">Day 1: Microservices & Core Architecture API Layouts</strong> — Focus on building robust, modular files rather than consolidating everything in one. Practice routing controllers.</li>
              <li><strong class="text-white">Day 2: Mock Databases & Schema Testing</strong> — Design high-throughput database structures and write transactional isolation criteria in SQLite/Local DB.</li>
              <li><strong class="text-white">Day 3: Memory Allocations, Heap Queues & Big-O Bounds</strong> — Practice O(N log N) sliding-window tasks.</li>
              <li><strong class="text-white">Day 4: Resume Integrity Alignment</strong> — Fill the detected keyword gaps such as {gaps_str} in experience bullet logs.</li>
              <li><strong class="text-white">Day 5: Interview Trial Readiness Drill</strong> — Tackle 4 tricky behavioral modules and practical coding assignments.</li>
              <li><strong class="text-white">Day 6: Cloud Native Deployment Infrastructure</strong> — Explore container orchestration, health ports and edge proxy boundaries.</li>
              <li><strong class="text-white">Day 7: Full Scale Mock Panel Review</strong> — Re-check the interactive questions and examine history trends!</li>
            </ol>
            <p class="text-[10px] text-gray-500 font-mono mt-2">Generated by Offline Portfolio Fallback Engine. Standard schema maps registered successfully.</p>
          </div>
        """
        
    return {
        "reply": connected_reply,
        "isPlanSuggested": is_plan,
        "studyPlanHTMLSnippet": html_snippet
    }

def main():
    payload = read_input()
    user_message = payload.get("userMessage", "")
    chat_history = payload.get("chatHistory", [])
    profile = payload.get("userProfile", {})
    results = payload.get("results", {})
    stored_memory = payload.get("storedMemory", [])
    
    use_real_ai = bool(os.environ.get("GROQ_API_KEY") or os.environ.get("GEMINI_API_KEY"))
    if not use_real_ai:
        write_output(get_fallback_data(user_message, profile, results, stored_memory))
        
    history_prompt = ""
    for h in chat_history:
        role = "Candidate" if h.get("role") == "user" else "Mentor"
        history_prompt += f"{role}: {h.get('text')}\n"
        
    gaps_list = []
    if results and results.get("skillGaps"):
        for g in results.get("skillGaps"):
            if isinstance(g, dict):
                gaps_list.append(f"{g.get('skillName')} ({g.get('priority')} Priority: {g.get('whyNeeded')})")
            else:
                gaps_list.append(str(g))
    gaps = ", ".join(gaps_list) if gaps_list else "None specified"
    
    resume_ats = results.get("resumeAnalysis", {}).get("atsScore", "Not Analyzed") if results else "Not Analyzed"
    improvements_list = results.get("resumeAnalysis", {}).get("improvements", []) if results else []
    resume_improvements = "\n- ".join(improvements_list) if improvements_list else "No active suggestions"
    
    mem_list = []
    for m in stored_memory:
        if isinstance(m, dict):
            mem_list.append(f"* Note: {m.get('note')} (Category: {m.get('category')})")
    memory_context = "\n".join(mem_list) if mem_list else "No custom preferences remembered."
    
    system_prompt = f"""You are a visionary, highly encouraging, and deeply technical AI Career Mentor.
You are mentoring a user named {profile.get("name", "Candidate")}.

Here is the synchronized platform intelligence context:
- Name: {profile.get("name", "Candidate")}
- Degree/Background: {profile.get("degree", "Technologist")}
- Career Goal: {profile.get("careerGoal", "Elite Engineer")}
- Current Known Skills: {", ".join(profile.get("knownSkills", [])) if profile.get("knownSkills") else "None specified"}.
- Detected Skill Gaps: {gaps}.
- Resume ATS Tracker Score: {resume_ats} / 100
- Needed Resume Enhancements:
- {resume_improvements}

- CUSTOM PREFERENCES IN THE MENTOR MEMORY STORAGE:
{memory_context}

Guidelines for detailed response:
1. Speak as an elite Silicon Valley Tech Advisor & Lead Architect. Give highly informative, extremely specific engineering advice. Mention real patterns (e.g., event loops, memory buffers, Redis caches, indices), rather than generic "work hard" tips.
2. If they ask to generate a "study plan" or "learning schedule" or "7-Day Study Plan", set "isPlanSuggested" to true and return a beautiful, custom HTML snippet in "studyPlanHTMLSnippet" (structured as a timeline, using Tailwind styles matching a high-contrast dark visual theme, using colors like text-cyan-400, bg-slate-900, text-gray-300).
3. If they ask a general question, keep "isPlanSuggested" as false, and "studyPlanHTMLSnippet" as null.
4. Keep the conversational reply concise, precise, and professional.

Respond with ONLY a clean JSON object containing:
{{
  "reply": "Your conversational reply. Highlight specific, actionable engineering designs. You may use standard markdown.",
  "isPlanSuggested": true or false,
  "studyPlanHTMLSnippet": "Your beautifully formatted, custom Tailwind-styled HTML study timeline, or null."
}}
No markdown backtick wraps around the JSON itself. Return strictly parseable JSON."""

    prompt_message = f"{system_prompt}\n\nChat History:\n{history_prompt}\nCandidate Message: {user_message}"
    
    try:
        text_output = call_llm(prompt_message, True)
        cleaned = text_output.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.replace("```json", "", 1).replace("```", "").strip()
        write_output(json.loads(cleaned))
    except Exception as e:
        sys.stderr.write(f"Error calling mentor chat: {e}\n")
        write_output(get_fallback_data(user_message, profile, results, stored_memory))

if __name__ == "__main__":
    main()
